name: maven-build

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 17, 18, 19 ]
    steps:
      - uses: actions/checkout@v3.1.0
      - name: setup-jdk-${{ matrix.java }}
        uses: actions/setup-java@v3.9.0
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'
          check-latest: true
      - name: build-jar
        run: mvn -B install
