on:
  schedule:
    - cron: '30 5 * * *'

jobs:
  test_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: setup-jdk-11
        uses: actions/setup-java@v3.5.1
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
          check-latest: true
      - name: check dependencies
        run: mvn dependency-check:check
